### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by lilyomo** [airingursb/bilibili-video#1]
File "F:\b\bilibili_video.py", line 171
    print "Succeed: av" + str(av)
                      ^
SyntaxError: invalid syntax

**Comment by yaodongli0810** [comment]
python版本

**Comment by yaodongli0810** [comment]
python版本，3？@Cloudiver

**Comment by lilyomo** [comment]
是的。

**Comment by airingursb** [comment]
@Cloudiver 不好意思，这个库很久没有维护了，不过应该还是可以跑的。请切换python2 运行。
